# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

# 去掉由pod引入的第三方库的警告，需要更新命令才生效
inhibit_all_warnings!

# pod 快速更新方法
# pod update --verbose --no-repo-update

target 'zhuaWaWa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for zhuaWaWa

    # BAHome 系列代码
    pod 'BANetManager'
    pod 'BAButton'
    pod 'BAAlert'
#    pod 'BAPickView'
    pod 'BATouchID'
    pod 'BATextView'
    pod 'BAAlertController'
    pod 'BAWKWebView'
    pod 'BATextField'
    pod 'BAGridView'

    # 在屏幕中间显示 加载框 类似于安卓的toast效果
    pod 'MBProgressHUD'
    
    # 空数据 的三方库
    pod 'DZNEmptyDataSet'
    
    # 内存泄露检测工具
    pod 'MLeaksFinder'
    
    # 空数据的处理
    pod 'NullSafe'

    # 友盟分享
    pod 'UMengUShare/UI'
    # 集成新浪微博 【友盟官网技术文档这里标点符号有错，导入的时候记得更改】
    pod 'UMengUShare/Social/Sina'
    # 集成微信
    pod 'UMengUShare/Social/WeChat'
    # 集成QQ
    pod 'UMengUShare/Social/QQ'
    # 集成支付宝
    pod 'UMengUShare/Social/AlipayShare'
    
    
    # 友盟统计
    pod 'UMengAnalytics-NO-IDFA'
    
    pod 'LBXAlertAction'
    pod 'ZYCornerRadius', git:'https://github.com/liuzhiyi1992/ZYCornerRadius.git',tag:'0.9.1'
    
    # 为滚动控件（UIScrollView, UITableView, UICollectionView）添加头部脚部刷新UI
    pod 'MJRefresh'
    pod 'IQKeyboardManager'
    pod 'SDCycleScrollView'
    pod 'YYModel'
    pod 'YYCategories'
    
    pod 'YYImage'
    pod 'YYWebImage'
    # 专门用于转换 Array/Dictionary -> 对象模型 主要用于JSON解析，基本都用这个框架（必会）
    pod 'MJExtension'
    pod 'HappyDNS'
    # 两个都是自动布局框架
    pod 'SDAutoLayout'
end
